---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS in Action: chapter 8 (EBS)'
Parameters:
  KeyName:
    Description: Key Pair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: sol
  VPC:
    Description: Just select the one and only default VPC
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: Just select one of the available subnets
    Type: AWS::EC2::Subnet::Id
  AttachVolume:
    Description: Should the volume be attached?
    Type: String
    Default: 'yes'
    AllowedValues:
    - 'yes'
    - 'no'

Conditions:
  Attached:
    Fn::Equals:
    - Ref: AttachVolume
    - 'yes'
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ec2
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:DescribeVolumes
            - ec2:CreateSnapshot
            - ec2:DescribeSnapshots
            - ec2:DeleteSnapshot
            Resource: "*"
  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: IamRole
  Server:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: IamInstanceProfile
      ImageId: ami-02e05347a68e9c76f
      InstanceType: t2.micro
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
      - Ref: SecurityGroup
      SubnetId:
        Ref: Subnet
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone:
        Fn::GetAtt:
        - Server
        - AvailabilityZone
      Size: '5'
      VolumeType: gp2
  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Condition: Attached
    Properties:
      Device: "/dev/xvdf"
      InstanceId:
        Ref: Server
      VolumeId:
        Ref: Volume
Outputs:
  PublicName:
    Value:
      Fn::GetAtt:
      - Server
      - PublicIp
    Description: Public name (connect via SSH as user ec2-user)
  VolumeId:
    Value:
      Ref: Volume
    Description: Volume id
